[general]
import = ["~/.cache/wal/colors-alacritty.toml"]
#import = ["~/.config/alacritty/alacritty-theme/themes/dark_pride.toml"]

[window]

opacity = 0.685

padding.x = 10
padding.y = 10

decorations = "FUll"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "Fira Code"
bold.family = "Fira Code"
italic.family = "Fira Code"
bold_italic.family = "Fira Code"

size = 8.0
