--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/berserk/655978.jpg"

-- Special
background="#080505"
foreground="#c1c0c0"
cursor="#c1c0c0"

-- Colors
color0="#080505"
color1="#724B4B"
color2="#9D2929"
color3="#996464"
color4="#946B6B"
color5="#AD7F80"
color6="#B48C8C"
color7="#c1c0c0"
color8="#665353"
color9="#724B4B"
color10="#9D2929"
color11="#996464"
color12="#946B6B"
color13="#AD7F80"
color14="#B48C8C"
color15="#c1c0c0"
