--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/unixporn-disc/1378714_upscayl_2x_realesrgan-x4plus.png"

-- Special
background="#110f0d"
foreground="#c3c3c2"
cursor="#c3c3c2"

-- Colors
color0="#110f0d"
color1="#304837"
color2="#46523E"
color3="#4E6852"
color4="#985C3E"
color5="#57966D"
color6="#A49D6F"
color7="#c3c3c2"
color8="#6c6558"
color9="#304837"
color10="#46523E"
color11="#4E6852"
color12="#985C3E"
color13="#57966D"
color14="#A49D6F"
color15="#c3c3c2"
