# Shell variables
# Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/berserk/655978.jpg"

# Special
background='#080505'
foreground='#c1c0c0'
cursor='#c1c0c0'

# Colors
color0='#080505'
color1='#724B4B'
color2='#9D2929'
color3='#996464'
color4='#946B6B'
color5='#AD7F80'
color6='#B48C8C'
color7='#c1c0c0'
color8='#665353'
color9='#724B4B'
color10='#9D2929'
color11='#996464'
color12='#946B6B'
color13='#AD7F80'
color14='#B48C8C'
color15='#c1c0c0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
