[colors.primary]
background = "#141210"
foreground = "#c4c3c3"

[colors.cursor]
text = "#141210"
cursor = "#c4c3c3"

[colors.vi_mode_cursor]
text = "#141210"
cursor = "#c4c3c3"

[colors.search.matches]
foreground = "#141210"
background = "#c4c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6e615a"
background = "#c4c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#141210"
red = "#807B85"
green = "#75B68D"
yellow = "#ADA09F"
blue = "#D4BEA0"
magenta = "#86D69B"
cyan = "#B3D58F"
white = "#c4c3c3"

[colors.bright]
black = "#6e615a"
red = "#807B85"
green = "#75B68D"
yellow = "#ADA09F"
blue = "#D4BEA0"
magenta = "#86D69B"
cyan = "#B3D58F"
white = "#c4c3c3"

[colors.dim]
black = "#c4c3c3"
red = "#807B85"
green = "#86D69B"
yellow = "#ADA09F"
blue = "#D4BEA0"
magenta = "#75B68D"
cyan = "#B3D58F"
white = "#6e615a"

