# Shell variables
# Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/unixporn-disc/M2A6OJS.png"

# Special
background='#0f1011'
foreground='#c3c3c3'
cursor='#c3c3c3'

# Colors
color0='#0f1011'
color1='#A38974'
color2='#7E7F81'
color3='#838383'
color4='#B0A68F'
color5='#DAC2A1'
color6='#D8C8A6'
color7='#c3c3c3'
color8='#59596d'
color9='#A38974'
color10='#7E7F81'
color11='#838383'
color12='#B0A68F'
color13='#DAC2A1'
color14='#D8C8A6'
color15='#c3c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
