# Shell variables
# Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/unixporn-disc/a_cartoon_of_a_woman_sitting_on_a_table_with_an_umbrella.png"

# Special
background='#141210'
foreground='#c4c3c3'
cursor='#c4c3c3'

# Colors
color0='#141210'
color1='#807B85'
color2='#75B68D'
color3='#ADA09F'
color4='#D4BEA0'
color5='#86D69B'
color6='#B3D58F'
color7='#c4c3c3'
color8='#6e615a'
color9='#807B85'
color10='#75B68D'
color11='#ADA09F'
color12='#D4BEA0'
color13='#86D69B'
color14='#B3D58F'
color15='#c4c3c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
