[colors.primary]
background = "#110f0d"
foreground = "#c3c3c2"

[colors.cursor]
text = "#110f0d"
cursor = "#c3c3c2"

[colors.vi_mode_cursor]
text = "#110f0d"
cursor = "#c3c3c2"

[colors.search.matches]
foreground = "#110f0d"
background = "#c3c3c2"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6c6558"
background = "#c3c3c2"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#110f0d"
red = "#304837"
green = "#46523E"
yellow = "#4E6852"
blue = "#985C3E"
magenta = "#57966D"
cyan = "#A49D6F"
white = "#c3c3c2"

[colors.bright]
black = "#6c6558"
red = "#304837"
green = "#46523E"
yellow = "#4E6852"
blue = "#985C3E"
magenta = "#57966D"
cyan = "#A49D6F"
white = "#c3c3c2"

[colors.dim]
black = "#c3c3c2"
red = "#304837"
green = "#57966D"
yellow = "#4E6852"
blue = "#985C3E"
magenta = "#46523E"
cyan = "#A49D6F"
white = "#6c6558"

