--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/unixporn-disc/M2A6OJS.png"

-- Special
background="#0f1011"
foreground="#c3c3c3"
cursor="#c3c3c3"

-- Colors
color0="#0f1011"
color1="#A38974"
color2="#7E7F81"
color3="#838383"
color4="#B0A68F"
color5="#DAC2A1"
color6="#D8C8A6"
color7="#c3c3c3"
color8="#59596d"
color9="#A38974"
color10="#7E7F81"
color11="#838383"
color12="#B0A68F"
color13="#DAC2A1"
color14="#D8C8A6"
color15="#c3c3c3"
