# Shell variables
# Generated by 'wal'
wallpaper="/home/bae/.config/hypr/wallpaper/unixporn-disc/1378714_upscayl_2x_realesrgan-x4plus.png"

# Special
background='#110f0d'
foreground='#c3c3c2'
cursor='#c3c3c2'

# Colors
color0='#110f0d'
color1='#304837'
color2='#46523E'
color3='#4E6852'
color4='#985C3E'
color5='#57966D'
color6='#A49D6F'
color7='#c3c3c2'
color8='#6c6558'
color9='#304837'
color10='#46523E'
color11='#4E6852'
color12='#985C3E'
color13='#57966D'
color14='#A49D6F'
color15='#c3c3c2'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
