[colors.primary]
background = "#080505"
foreground = "#c1c0c0"

[colors.cursor]
text = "#080505"
cursor = "#c1c0c0"

[colors.vi_mode_cursor]
text = "#080505"
cursor = "#c1c0c0"

[colors.search.matches]
foreground = "#080505"
background = "#c1c0c0"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#665353"
background = "#c1c0c0"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#080505"
red = "#724B4B"
green = "#9D2929"
yellow = "#996464"
blue = "#946B6B"
magenta = "#AD7F80"
cyan = "#B48C8C"
white = "#c1c0c0"

[colors.bright]
black = "#665353"
red = "#724B4B"
green = "#9D2929"
yellow = "#996464"
blue = "#946B6B"
magenta = "#AD7F80"
cyan = "#B48C8C"
white = "#c1c0c0"

[colors.dim]
black = "#c1c0c0"
red = "#724B4B"
green = "#AD7F80"
yellow = "#996464"
blue = "#946B6B"
magenta = "#9D2929"
cyan = "#B48C8C"
white = "#665353"

