[colors.primary]
background = "#0f1011"
foreground = "#c3c3c3"

[colors.cursor]
text = "#0f1011"
cursor = "#c3c3c3"

[colors.vi_mode_cursor]
text = "#0f1011"
cursor = "#c3c3c3"

[colors.search.matches]
foreground = "#0f1011"
background = "#c3c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#59596d"
background = "#c3c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0f1011"
red = "#A38974"
green = "#7E7F81"
yellow = "#838383"
blue = "#B0A68F"
magenta = "#DAC2A1"
cyan = "#D8C8A6"
white = "#c3c3c3"

[colors.bright]
black = "#59596d"
red = "#A38974"
green = "#7E7F81"
yellow = "#838383"
blue = "#B0A68F"
magenta = "#DAC2A1"
cyan = "#D8C8A6"
white = "#c3c3c3"

[colors.dim]
black = "#c3c3c3"
red = "#A38974"
green = "#DAC2A1"
yellow = "#838383"
blue = "#B0A68F"
magenta = "#7E7F81"
cyan = "#D8C8A6"
white = "#59596d"

